# Generated by Django 3.1.3 on 2020-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_order_orderlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
